name: adhirat
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  audioplayers: ^4.1.0
  url_launcher: ^6.1.11
  open_filex: ^4.3.2
  zoom_widget: ^2.0.1
  get: ^4.6.5
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  side_navigation: ^1.0.4
  csv: ^5.0.2
  intl_phone_number_input:
  flutter_staggered_grid_view: ^0.6.2
  permission_handler: ^10.2.0
  record: ^4.4.4
  video_thumbnail: ^0.5.3
  video_player: ^2.6.1
  percent_indicator: ^4.2.3
  share_plus: ^7.0.0
  http: ^0.13.6
  path_provider: ^2.0.15
  flutter_pdfview: ^1.3.1
  icalendar_parser:
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/file/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
